In [222]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [223]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()
iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [224]:
df=pd.DataFrame(data=iris_dataset.data,columns=iris_dataset.feature_names)

In [225]:
df['flower']=iris_dataset.target
df['flower']=df['flower'].apply(lambda x:iris_dataset.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [226]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris_dataset.data,iris_dataset.target,test_size=0.3)

In [227]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9555555555555556

In [228]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='linear',gamma='auto',C=10),iris_dataset.data,iris_dataset.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [229]:
cross_val_score(SVC(kernel='rbf',gamma='auto',C=10),iris_dataset.data,iris_dataset.target)


array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [230]:
cross_val_score(SVC(kernel='linear',gamma='auto',C=20),iris_dataset.data,iris_dataset.target)


array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [231]:
kernels=['rbf','linear']
c_val=[1,10,20]
avg_scores={}
for k in kernels:
    for c in c_val:
        c_scores=cross_val_score(SVC(kernel=k,C=c,gamma='auto'),iris_dataset.data,iris_dataset.target,cv=5)
        avg_scores[k+'_'+str(c)]=np.average(c_scores)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

KERNEL
---
A kernel transforms the input data into a higher-dimensional space so SVM can separate classes that are not linearly separable.

🔵 What is the RBF Kernel?
---
The RBF (Radial Basis Function) kernel creates non-linear decision boundaries.

🎯 Why RBF is Used?
---
Because:

It handles non-linear data extremely well.

It can create complex shapes for classification.

Works in most real-world datasets.

GridSearchCV
---

GridSearchCV is a tool in scikit-learn used to find the best hyperparameters for a machine-learning model by trying every possible combination from a grid (a list) of values you provide.

It stands for:

Grid Search + Cross Validation

🧠 Why we need GridSearchCV?
---
Models depend on hyperparameters like:

k in KNN

C, gamma in SVM

max_depth in Decision Trees

n_estimators in Random Forest

Choosing them manually is difficult.
GridSearchCV tests many combinations and picks the one with best accuracy.

⚙️ How GridSearchCV Works (Simple Steps)
---
Step 1: You define the model

Example: SVM

Step 2: You define the parameter grid

Example:

    param_grid = {
        'C': [0.1, 1, 10],
        'gamma': [0.001, 0.01, 0.1],
        'kernel': ['rbf']
    }
Step 3: GridSearchCV tries ALL combinations
Like:

C=0.1, gamma=0.001

C=0.1, gamma=0.01

C=0.1, gamma=0.1

C=1, gamma=0.001

… etc.

Step 4: For each combination, it performs cross-validation
This prevents overfitting.

Step 5: Returns the best parameters and best model

In [232]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)
clf.fit(iris_dataset.data,iris_dataset.target)
clf.cv_results_

{'mean_fit_time': array([0.00159912, 0.00099754, 0.00099707, 0.00120277, 0.        ,
        0.00080442]),
 'std_fit_time': array([8.01648533e-04, 4.77551878e-06, 8.92178111e-04, 3.95126196e-04,
        0.00000000e+00, 4.02251755e-04]),
 'mean_score_time': array([0.00099983, 0.0006031 , 0.00060148, 0.0025979 , 0.        ,
        0.        ]),
 'std_score_time': array([0.00063186, 0.00049243, 0.00049111, 0.00325927, 0.        ,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [233]:
df=pd.DataFrame(clf.cv_results_)
# df
df[['param_C','param_kernel','mean_test_score','rank_test_score']]

param_C param_kernel  mean_test_score  rank_test_score
0        1          rbf         0.980000                1
1        1       linear         0.980000                1
2       10          rbf         0.980000                1
3       10       linear         0.973333                4
4       20          rbf         0.966667                5
5       20       linear         0.966667                6

In [234]:
clf.best_score_

0.9800000000000001

In [235]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

Disadvantage of GridSearchCV:
---
Computational cost of GridSearchCV is very high


To tackle the disadvatage of GridSearchCV ,sklearn library introduces new class called "RandomizedSearchCV"

RandomizedSearchCV
---

RandomizedSearchCV is a hyperparameter tuning technique in scikit-learn that randomly selects combinations of hyperparameters instead of trying every possible one (like GridSearchCV).

It is often faster and more efficient, especially when you have many hyperparameters or large search spaces.

🚀 Why RandomizedSearchCV?
---
Because GridSearchCV becomes slow when:

    You have many parameters

    Each parameter has many possible values

    The model is computationally expensive

RandomizedSearchCV solves this by sampling a fixed number of random combinations.

🔍 How RandomizedSearchCV Works
---
Step 1: You define parameter ranges, NOT all values

Example:

    param_dist = {
        'C': [0.1, 1, 10, 100, 1000],
        'gamma': [0.0001, 0.001, 0.01, 0.1],
        'kernel': ['rbf']
    }

Step 2: Instead of testing all combinations

    GridSearchCV tests all = 5 × 4 × 1 = 20 trials

    RandomizedSearchCV tests, say, 5 or 10 random combinations only.

Step 3: It applies cross-validation on each random combination

    → Helps prevent overfitting.    

Step 4: It returns:

    Best hyperparameters

    Best model

    Best CV score

In [236]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)

rs.fit(iris_dataset.data,iris_dataset.target)
df=pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
df    

param_C param_kernel  mean_test_score
0       10       linear         0.973333
1        1       linear         0.980000

MODEL SELECTION USING HYPERPARAMETER TUNING
---

In [237]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [238]:
model_params={

    'svm':{
    'model':SVC(gamma='auto'),
    'params':{    
        'C':[1,10,20],
        'kernel':['rbf','linear']
    }
},

    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{    
            'n_estimators':[1,5,10],
        }
},

    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{    
            'C':[1,5,10],
        }
}



}

In [239]:
scores=[]
for model_name,model_parameter in model_params.items():
    clf=GridSearchCV(model_parameter['model'],model_parameter['params'],cv=5,return_train_score=False)
    clf.fit(iris_dataset.data,iris_dataset.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    }
    )

C:\Users\kevin\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\kevin\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\kevin\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\kevin\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_mo

In [240]:
df=pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}