In [430]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [431]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [432]:
iris_dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [433]:
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [434]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [435]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier


In [436]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris_dataset.data,iris_dataset.target,test_size=0.3)

In [437]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [438]:
score_lr=[]
score_svc=[]
score_rf=[]
for train_index,test_index in folds.split(iris_dataset.data,iris_dataset.target):
    x_train,x_test,y_train,y_test=iris_dataset.data[train_index],iris_dataset.data[test_index],iris_dataset.target[train_index],iris_dataset.target[test_index]
    score_lr.append(get_score(LogisticRegression(max_iter=2000),x_train,x_test,y_train,y_test))
    score_svc.append(get_score(SVC(gamma='auto'),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))


In [439]:
score_lr

[0.98, 0.96, 0.98]

In [440]:
score_svc

[0.98, 0.98, 0.96]

In [441]:
score_rf

[0.98, 0.94, 0.92]

cross_val_score function
------------------------

Logistic Regression

In [451]:
from sklearn.model_selection import cross_val_score
lr_score=cross_val_score(LogisticRegression(max_iter=2000),iris_dataset.data,iris_dataset.target,cv=3)
lr_score

array([0.98, 0.96, 0.98])

In [443]:
np.average(lr_score)

0.9733333333333333

Support Vector Machine (SVM)

In [444]:
svc_score=cross_val_score(SVC(gamma='auto'),iris_dataset.data,iris_dataset.target,cv=3)
svc_score

array([0.98, 0.98, 0.96])

In [445]:
np.average(svc_score)

0.9733333333333333

Random Forest

In [446]:
rf_score=cross_val_score(RandomForestClassifier(n_estimators=10),iris_dataset.data,iris_dataset.target,cv=3)
rf_score

array([0.96, 0.98, 0.94])

In [447]:
np.average(rf_score)

0.96

Decision Tree

In [448]:
decision_scores = cross_val_score(DecisionTreeClassifier(), iris_dataset.data, iris_dataset.target,cv=3)
decision_scores

array([0.98, 0.92, 1.  ])

In [449]:
np.average(rf_score)


0.96

Best score so far is from both SVM and Logistic Regression

    -SVM:97.3333

    -LOGISTIC REGRESSION:97.33