In [661]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.datasets import load_digits
digit_dataset=load_digits()

In [663]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digit_dataset.data,digit_dataset.target,test_size=0.3)

K-Fold Cross Validation Method

In [665]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)


In [666]:
for train_index,test_index in kf.split([0,1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [667]:
print(digit_dataset.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [668]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

def get_score(model, x_train,x_test,y_train,y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

score_logistic_reg=[]
score_svm=[]
score_random_forest=[]
for train_index,test_index in folds.split(digit_dataset.data,digit_dataset.target):
    x_train,x_test,y_train,y_test=digit_dataset.data[train_index],digit_dataset.data[test_index],digit_dataset.target[train_index],digit_dataset.target[test_index]
    score_logistic_reg.append(get_score(LogisticRegression(max_iter=2000),x_train,x_test,y_train,y_test)*100)
    score_svm.append(get_score(SVC(gamma='auto'),x_train,x_test,y_train,y_test)*100)
    score_random_forest.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test)*100)


In [669]:
score_logistic_reg

[91.98664440734558, 94.15692821368948, 91.65275459098497]

In [670]:
score_svm

[38.06343906510851, 41.068447412353926, 51.25208681135225]

In [671]:

score_random_forest

[94.49081803005008, 94.82470784641069, 91.31886477462437]

cross_val_score function
------------------------

Logistic regression model performance using cross_val_score

In [682]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='saga',max_iter=2000),digit_dataset.data,digit_dataset.target,cv=3)

array([0.92153589, 0.94156928, 0.91819699])

SVM model performance using cross_val_score

In [688]:
cross_val_score(SVC(gamma='auto'),digit_dataset.data,digit_dataset.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

Random Forest model performance using cross_val_score

In [689]:
cross_val_score(RandomForestClassifier(n_estimators=40),digit_dataset.data,digit_dataset.target,cv=3)


array([0.93823038, 0.95492487, 0.92320534])

In [691]:
cross_val_score(RandomForestClassifier(n_estimators=15),digit_dataset.data,digit_dataset.target,cv=3)


array([0.89649416, 0.9148581 , 0.9148581 ])